/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import model.Paciente;

    
/**
 *
 * @author Campos\
 */
public final class TelaPacientes extends javax.swing.JInternalFrame {
    private final repository.PacienteRepositorio repo = new repository.PacienteRepositorio();
    /**
     * Creates new form TelaPacientes
     */
    public TelaPacientes() {
        initComponents();
        preencherTabela();
        carregarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCpf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtData = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtConvenio = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        txtCodigo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setText("Nome:");

        txtNome.addActionListener(this::txtNomeActionPerformed);

        jLabel2.setText("CPF:");

        txtCpf.addActionListener(this::txtCpfActionPerformed);

        jLabel3.setText("Data de nascimento:");

        txtData.addActionListener(this::txtDataActionPerformed);

        txtEmail.addActionListener(this::txtEmailActionPerformed);

        jLabel4.setText("Telefone:");

        jLabel5.setText("E-mail:");

        txtConvenio.addActionListener(this::txtConvenioActionPerformed);

        txtTelefone.addActionListener(this::txtTelefoneActionPerformed);

        jLabel6.setText("Convênio:");

        jButton1.setBackground(new java.awt.Color(0, 102, 51));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Inserir");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setBackground(new java.awt.Color(0, 0, 153));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Consultar");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setBackground(new java.awt.Color(255, 255, 0));
        jButton3.setText("Alterar");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton4.setBackground(new java.awt.Color(204, 0, 0));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Excluir");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "CPF", "Data de nascimento", "Telefone", "E-mail", "Convênio"
            }
        ));
        Tabela.setRowHeight(26);
        Tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Tabela);

        txtCodigo.addActionListener(this::txtCodigoActionPerformed);

        jLabel8.setText("Codigo:");

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CADASTRO DE PACIENTE");
        jLabel7.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(474, 474, 474))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(441, 441, 441)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(336, 336, 336)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtConvenio, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(92, 92, 92)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtConvenio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(68, 68, 68)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfActionPerformed

    private void txtDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtConvenioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConvenioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConvenioActionPerformed

    private void txtTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefoneActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    if (!validarCampos()) {
        return;
    }

    model.Paciente paciente = new model.Paciente();

    paciente.setNome(txtNome.getText().trim());
    paciente.setCpf(txtCpf.getText().trim());
    paciente.setDataNascimento(txtData.getText().trim()); 
    paciente.setTelefone(txtTelefone.getText().trim());
    paciente.setEmail(txtEmail.getText().trim());
    // Normaliza o convênio para maiúsculas (SO, LP, AMS, IP)
    paciente.setConvenio(txtConvenio.getText().trim().toUpperCase());

    repo.salvar(paciente);

    javax.swing.JOptionPane.showMessageDialog(this, "Paciente cadastrado com sucesso!");

    limparCampos();
    preencherTabela(); 



    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String textoCodigo = txtCodigo.getText().trim();

    if (textoCodigo.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Digite o código do paciente para buscar!");
        txtCodigo.requestFocus();
        return;
    }

    try {
        int codigo = Integer.parseInt(textoCodigo);
        Paciente p = repo.buscarPorCodigo(codigo); // Chama o método do repositório

        if (p != null) {
            // Preenche os campos do formulário com os dados retornados
            txtNome.setText(p.getNome());
            txtCpf.setText(p.getCpf());
            txtData.setText(p.getDataNascimento());
            txtTelefone.setText(p.getTelefone());
            txtEmail.setText(p.getEmail());
            txtConvenio.setText(p.getConvenio());
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Paciente com código " + codigo + " não foi encontrado!");
        }
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, " O campo código deve conter apenas números inteiros!");
    }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
        if (txtCodigo.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Informe o código do paciente que deseja alterar!");
            txtCodigo.requestFocus();
            return;
        }

        if (!validarCampos()) {
            return; // Garante que os novos dados editados estejam no padrão
        }

        model.Paciente paciente = new model.Paciente();
        paciente.setCodigo(Integer.parseInt(txtCodigo.getText().trim()));
        paciente.setNome(txtNome.getText().trim());
        paciente.setCpf(txtCpf.getText().trim());
        paciente.setDataNascimento(txtData.getText().trim());
        paciente.setTelefone(txtTelefone.getText().trim());
        paciente.setEmail(txtEmail.getText().trim());
        paciente.setConvenio(txtConvenio.getText().trim());

        boolean sucesso = repo.alterar(paciente);

        if (sucesso) {
            javax.swing.JOptionPane.showMessageDialog(this, "Paciente alterado com sucesso!");
            limparCampos();
            preencherTabela();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Código não encontrado para alteração!");
        }

    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Digite um código numérico válido!");
    }
    
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
    try {
        if (txtCodigo.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite o código do paciente que deseja excluir!");
            return;
        }

        int codigo = Integer.parseInt(txtCodigo.getText().trim());

        int resposta = JOptionPane.showConfirmDialog(
            this, 
            "Confirma a exclusão do paciente código " + codigo + "?", 
            "Excluir Paciente", 
            JOptionPane.YES_NO_OPTION
        );

        if (resposta == JOptionPane.YES_OPTION) {
            boolean removido = repo.excluirPorCodigo(codigo);

            if (removido) {
                JOptionPane.showMessageDialog(this, "Paciente excluído com sucesso!");
                limparCampos();     // Limpa todos os campos (inclusive o txtCodigo)
                preencherTabela();  // Atualiza a tabela na tela
            } else {
                JOptionPane.showMessageDialog(this, "Não foi encontrado paciente com o código " + codigo);
            }
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Digite apenas números no campo Código!");
    }  
    }//GEN-LAST:event_jButton4ActionPerformed

    private void TabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaMouseClicked
        int linha = Tabela.getSelectedRow();
if (linha != -1) {
    txtCodigo.setText(Tabela.getValueAt(linha, 0).toString());
    txtNome.setText(Tabela.getValueAt(linha, 1).toString());
    txtCpf.setText(Tabela.getValueAt(linha, 2).toString());
    txtData.setText(Tabela.getValueAt(linha, 3).toString());
    txtTelefone.setText(Tabela.getValueAt(linha, 4).toString());
    txtEmail.setText(Tabela.getValueAt(linha, 5).toString());
    txtConvenio.setText(Tabela.getValueAt(linha, 6).toString());
}
        // TODO add your handling code here:
    }//GEN-LAST:event_TabelaMouseClicked
public void preencherTabela() {
   
    javax.swing.table.DefaultTableModel model =
            (javax.swing.table.DefaultTableModel) Tabela.getModel();

    model.setRowCount(0);

    java.util.List<model.Paciente> lista = repo.listarTodos();

    System.out.println(
            ">>> QUANTIDADE DE PACIENTES NO BANCO: " + lista.size()
    );

    for (model.Paciente p : lista) {

        model.addRow(new Object[]{
            p.getCodigo(),
            p.getNome(),
            p.getCpf(),
            p.getDataNascimento(),
            p.getTelefone(),
            p.getEmail(),
            p.getConvenio()
        });
    }
}
private void limparCampos() {
    txtCodigo.setText("");
    txtNome.setText("");
    txtCpf.setText("");
    txtData.setText("");
    txtTelefone.setText("");
    txtEmail.setText("");
    txtConvenio.setText("");
    
    txtCodigo.requestFocus();

}
private boolean validarCampos() {
    if (txtNome.getText().trim().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Informe o Nome do paciente!");
        txtNome.requestFocus();
        return false;
    }

    // CPF: exatamente 11 dígitos
    if (!txtCpf.getText().matches("\\d{11}")) {
        javax.swing.JOptionPane.showMessageDialog(this, "O CPF deve conter exatamente 11 números!");
        txtCpf.requestFocus();
        return false;
    }

    // Data de Nascimento: exatamente 8 dígitos
    if (!txtData.getText().matches("\\d{8}")) {
        javax.swing.JOptionPane.showMessageDialog(this, "A Data de Nascimento deve conter exatamente 8 números!");
        txtData.requestFocus();
        return false;
    }

    // Telefone: exatamente 11 dígitos
    if (!txtTelefone.getText().matches("\\d{11}")) {
        javax.swing.JOptionPane.showMessageDialog(this, "O Telefone deve conter exatamente 11 números!");
        txtTelefone.requestFocus();
        return false;
    }

    // E-mail: obrigatório terminar em @gmail.com
    if (!txtEmail.getText().trim().toLowerCase().endsWith("@gmail.com")) {
        javax.swing.JOptionPane.showMessageDialog(this, "O E-mail deve terminar com @gmail.com!");
        txtEmail.requestFocus();
        return false;
    }
    String convenio = txtConvenio.getText().trim().toLowerCase();

        if (!convenio.equals("so") && !convenio.equals("lp") && !convenio.equals("ams") && !convenio.equals("ip")) {
        javax.swing.JOptionPane.showMessageDialog(this, "Convênio inválido! Permitidos apenas: SO, LP, AMS ou IP.");
        txtConvenio.requestFocus();
        return false;
}

    return true;
}
private void carregarTabela() {
    
    javax.swing.table.DefaultTableModel model =
            (javax.swing.table.DefaultTableModel) Tabela.getModel();

    model.setRowCount(0);

    java.util.List<model.Paciente> lista = repo.listarTodos();

    for (model.Paciente p : lista) {

        model.addRow(new Object[]{
            p.getCodigo(),
            p.getNome(),
            p.getCpf(),
            p.getDataNascimento(),
            p.getTelefone(),
            p.getEmail(),
            p.getConvenio()
        });
    }
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabela;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtConvenio;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}